name: "Assign Reviewers to PR"

on:
  pull_request:
    types: [opened, ready_for_review, reopened, review_requested, review_request_removed]

jobs:
  assign-pr-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Reviewers to PR"
      uses: itsOliverBott/assign-pr-reviewers@release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        users: "jessica-tw, mdcpmoreira, lucasdittrichzup, GuillaumeFalourd"
        ignore-drafts: true